import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs';
import Header from "./_components/Header";
import { Toaster } from "~/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen w-screen bg-[#1B262C] font-itim">
        <Header />
        {children}
        <Toaster />
        </body>
    </html>
    </ClerkProvider>
  );
}
